[program:birdie-api]
directory=/opt/birdie/app/backend
command=/opt/birdie/venv/bin/uvicorn main:app --host 127.0.0.1 --port 8000
autostart=true
autorestart=true
stderr_logfile=/var/log/birdie-api.err.log
stdout_logfile=/var/log/birdie-api.out.log
user=birdie
environment=PYTHONPATH="/opt/birdie/app/backend"
